### ISSUE TITLE
Add support of RDMA Infiniband counter

### ISSUE THREAD

**Issue by avnf** [sam-andaluri/grafonnet-dashboard#1]
Current version of rdma_counters_exporter.py only exports rdma counters of RoCE RDMA over Ethernet devices (hw_counters).
Infiniband devices have different counters set (port counters):
/sys/class/infiniband/{nic}/ports/1/counters
https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband
like 
/sys/class/infiniband/<device>/ports/<port-num>/counters/port_xmit_data
/sys/class/infiniband/<device>/ports/<port-num>/counters/port_rcv_data
/sys/class/infiniband/<device>/ports/<port-num>/counters/port_xmit_packets
/sys/class/infiniband/<device>/ports/<port-num>/counters/port_rcv_packets

HW counters are for RDMA diagnostics according to https://enterprise-support.nvidia.com/s/article/understanding-mlx5-linux-counters-and-status-parameters

Could you please implement RDMA counters too? With rdma counters, hw counters and nvlink counters it will be larger picture of GPU and fast networks usage.

**Comment by sam-andaluri** [comment]
Yes, good point. I will add it. Thank you for your feedback.

**Comment by sam-andaluri** [comment]
This is done with latest change. Thank you.
